### ISSUE TITLE
Xplr Neovim plugin development - Thoughts/Ideas/Improvements

### ISSUE THREAD

**Issue by fhill2** [sayanarijit/xplr#316]
After being able to require C modules inside Xplr I've started playing around with [nvim](https://github.com/fhill2/xplr.nvim) [xplr](https://github.com/fhill2/nvim.xplr) plugin pairs to integrate xplr into nvim.
Xplr is my favourite file manager and having xplr seamlessly integrate within xplr would be an ideal workflow.

### Starting features and implementation status
features of nnn fork of xplr: mappings, layout - working
Hover selection to nvim - currently unstable
open selection in nvim - through msgpack - working, would like to create some additional configuration so users can decide how they would like to open
simple msgpack API callings custom functions/commands from xplr functions - working

### Ideas - why? 
If the relevant xplr data is available within nvim, the user can do whatever they want with it. 
e.g: Send xplr selected files to qflist, preview hovered file in telescope driven previews (working on atm as an extra feature, very awesome :D ), change cwd, modify other plugins based on xplr data (switch nvim file managers cwd), run custom lua functions inside nvim on xplr selected files...

### My questions
Do you know of anyone already creating something similar?  If so, would could work together. 
Any other features that would be a good addition to above? 

___
And regarding hover selection instability, I was trying to find a way to access the hover selection in the lua environment (to send it over msgpack). Is this possible?

Currently the hover selection is implemented like this:  
xplr keybind triggers xplr lua function that executes `StartFifo`  and calls an nvim function that connects to pipe using libuv (job) on nvim side.
Currently sometimes get `broken pipe error` or xplr closing when executing this function which most likely can be fixed by working on it some more, but feels like this would be a lot cleaner doing `xplr lua env --> nvim lua env` with msgpack and bypassing pipes completely.
___

### Testing
if anyone would like to try out the plugins above, let me know about the install process etc, any feedback/improvements, that would be awesome, a major help.
It's definitely a WIP state atm, just uploaded so I can share to test. There are definitely some bugs. (hover selection/Telescope previewer is broken atm), apart from that all the other features should work.

**Comment by sayanarijit** [comment]
Hey awesome work! I'll try them out and provide feedback. I as of now don't know if anyone's working on it, but I'll give a shoutout to the community to see if anyone's interested. I can be a little slow nowadays, but I'll definitely help out as well.

**Comment by sayanarijit** [comment]
Please give me some time to play around with the plugins. I'll be able to answer the remaining questions after that.

**Comment by sayanarijit** [comment]
Hey @fhill2 I was trying it out but ran into this.

```
Error detected while processing /home/sayanarijit/.config/nvim/init.vim:
line  785:
E5108: Error executing lua /home/sayanarijit/.vim/plugged/xplr.nvim/lua/xplr.lua:2: module 'log1' not found:
        no field package.preload['log1']
        no file './log1.lua'
        no file '/usr/share/luajit-2.0.5/log1.lua'
```

**Comment by sayanarijit** [comment]
Also, I think it's better to add the lua dependencies as git submodules instead of requesting the users to install luarocks.

**Comment by fhill2** [comment]
Thank you for the shoutout!
That error you are getting is fixed now.
Yes that's a good idea, I'm going to go ahead and move the lua deps to submodules.

**Comment by fhill2** [comment]
I've also fixed the previewer so it is now able to be tested.

**Comment by sayanarijit** [comment]
Still facing some issues. I'll create issues in the respective repos.

**Comment by sayanarijit** [comment]
What do you think if we let xplr load multiple config files, each overwriting the previous one using some CLI option like `-C`? This way all we'll need is the `xplr.nvim` repo. It can make xplr load the required config using that CLI option.

**Comment by fhill2** [comment]
@sayanarijit 
Thank you for your input again. I've fixed the issues you have discovered.

This is a great idea. It would be a helpful feature.
 
Thinking about this more:
I can pass down an environment variable of the `xplr.nvim` repo's installation path from nvim to xplr running in the job so xplr can find all of the files and setup config.
So everything can be in 1 repo regardless.
However, if you are going to implement this, I will use this way you have described.

**Comment by sayanarijit** [comment]
>  I can pass xplr.nvim repo's installation path via an env var from nvim to xplr running in the job so xplr can find all of the files and setup config.

Currently, xplr loads config at startup and from only one config file. So I can't see a way to load both `~/.config/xplr/init.lua` and `~/.vim/plugged/xplr.nvim/lua/xplr.lua` during startup. But yes, passing the path is also required.

**Comment by fhill2** [comment]
> > I can pass xplr.nvim repo's installation path via an env var from nvim to xplr running in the job so xplr can find all of the files and setup config.
> 
> Currently, xplr loads config at startup and from only one config file. So I can't see a way to load both `~/.config/xplr/init.lua` and `~/.vim/plugged/xplr.nvim/lua/xplr.lua` during startup. But yes, passing the path is also required.

I understand now, yeah no way of loading both files without user doing it manually :thumsbup:

**Comment by sayanarijit** [comment]
@fhill2 added support for extra config in the main branch. Haven't published yet.

**Comment by fhill2** [comment]
> @fhill2 added support for extra config in the main branch. Haven't published yet.

Awesome, thank you @sayanarijit.  
I'll test this out later today and work on merging `xplr.nvim` `nvim.xplr` making use of this.

**Comment by sayanarijit** [comment]
FYI I have added the plugin in [awesome-integrations](https://arijitbasu.in/xplr/en/awesome-integrations.html). Hope this helps.

**Comment by fhill2** [comment]
@sayanarijit Thank you.
Now that I'm happy with the installation process, I'll also post on the neovim reddit and [awesome-neovim](https://github.com/rockerBOO/awesome-neovim), which usually brings in some initial testers.

**Comment by sayanarijit** [comment]
To summarise, we have a standalone [nvim.xplr](https://github.com/fhill2/xplr.nvim) which uses msgpack for communication. But due to the complex nature of msgpack communication, and the many external requirements, turns out it was probably not the best way to do it.

For now, [xplr.vim](https://github.com/sayanarijit/xplr.vim) works well enough for most requirements, but anyone interested please feel free to improve upon this plugin, or create a better one. I'd recommend keeping the complexity and external requirements as low as possible. And only implement one feature at a time to make sure we're only implementing things we really need and we can maintain.

Thank you for the work you've done in xplr.nvim. Even if it has been archived, I think it will provide a good starting point and inspiration for interesting features for the next cool plugin (if any). But for now, I'm closing this issue.
