### ISSUE TITLE
Helix editor panics when started from xplr

### ISSUE THREAD

**Issue by Omnikar** [sayanarijit/xplr#449]
* OS: MacOS 11.2.1
* Terminal: iTerm2 3.4.12
* xplr version: 0.17.2
* Helix version: source build from commit [`368064e3`](https://github.com/helix-editor/helix/tree/368064e3)

When I try to start Helix from xplr, either via `:e` or even by typing `hx` into the shell opened by `:!`, it panics with the following panic message from crossterm:
```
thread 'main' panicked at 'reader source not set'
```
The panic message also gives that it occurred at `src/event/read.rs:38:30` in crossterm.

**Comment by sayanarijit** [comment]
Thanks for reporting.

Effective line: https://github.com/crossterm-rs/crossterm/blob/9bc5cd3527a2d26caa6e2ccdc499beb4764fca95/src/event/read.rs#L38

**Comment by sayanarijit** [comment]
The problem seems to be in macOS. But works find on Linux (tested on the latest Manjaro).

**Comment by sayanarijit** [comment]
The deepest I could investigate was upto [this function](https://github.com/crossterm-rs/crossterm/blob/9bc5cd3527/src/event/sys/unix/file_descriptor.rs#L67) where helix tries to create a file descriptor pointing to the standard input or `/dev/tty` and apparently panics.

So I tried to run the following code from inside xplr terminal, hoping for it to panic:

```rust
use libc;use std::fs;use std::os::unix::io::{IntoRawFd, RawFd};

fn main() {
    unsafe { libc::isatty(libc::STDIN_FILENO) };
    fs::OpenOptions::new().read(true).write(true).open("/dev/tty").unwrap().into_raw_fd();
}
```

But it ran successfully.

**Comment by sayanarijit** [comment]
Got some helpful references from the crossterm discord channel:

- https://github.com/crossterm-rs/crossterm/issues/396
- https://github.com/crossterm-rs/crossterm/pull/407
- https://github.com/crossterm-rs/crossterm/issues/500

**Comment by Omnikar** [comment]
Oh, it looks like https://github.com/crossterm-rs/crossterm/issues/500 is the same issue as what prevented Helix's "pipe into a buffer on startup" feature from working on MacOS.

**Comment by sayanarijit** [comment]
Seems like it's fixed in the latest version of helix editor.

![helix-xplr](https://user-images.githubusercontent.com/11632726/177101019-fc9d3ca8-fb68-4d79-8c8e-fa5825f5a9f3.gif)

Hence, closing this issue.

**Comment by Omnikar** [comment]
> Seems like it's fixed in the latest version of helix editor.

I updated to the latest version of Helix, but I'm still getting the same exact error.

**Comment by sayanarijit** [comment]
Can you confirm the correct binary is run in the xplr shell? Spawn the shell using :! and check version "$EDITOR --version"

**Comment by Omnikar** [comment]
> Can you confirm the correct binary is run in the xplr shell? Spawn the shell using :! and check version "$EDITOR --version"

It's Helix `22.05`, the latest version.

**Comment by tait-adam** [comment]
Was there any solution to this in the end?

• MacOS 11.7
• Kitty terminal 0.26.2
• xplr 0.19.3
• hx 22.08.1

Having the same problem

**Comment by sayanarijit** [comment]
Ah, so it's macOS specific. I currently don't have access to a macOS, but it sounds like the issue is related to one of the [crossterm issues linked above](https://github.com/sayanarijit/xplr/issues/449#issuecomment-1052020178). Need help to confirm this by a macOS user.

**Comment by taupiqueur** [comment]
I’ve been able to start Helix from xplr on macOS using @yyogo’s patch.

https://github.com/helix-editor/helix/issues/2111

**Comment by tait-adam** [comment]
> I’ve been able to start Helix from xplr on macOS using @yyogo’s patch.
> 
> [helix-editor/helix#2111](https://github.com/helix-editor/helix/issues/2111)

Works perfectly. Thanks

**Comment by sayanarijit** [comment]
Hope it gets fixed in crossterm/helix soon. Closing this.
